version: '3.1'

services:
  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    build:
      context: ./
      dockerfile: mysql/Dockerfile
    environment:
      - MYSQL_HOST=$MYSQL_HOST
      - MYSQL_PORT=$MYSQL_PORT
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
#    command: mysqld --character-set-server=$MYSQL_CHARSET --collation-server=$MYSQL_COLLATION

  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    build:
      context: ./
      dockerfile: nginx/Dockerfile
    links:
      - php
    depends_on:
      - php

  php:
    container_name: ${COMPOSE_PROJECT_NAME}_php
    build:
      context: ./
      dockerfile: php/Dockerfile
    env_file:
      - .env
    links:
      - mysql
    depends_on:
      - mysql
    working_dir: /srv
