# 
# more information can be found here http://sonata-project.org/bundles/news
#
nz_portfolio:
    permalink_generator: nz.portfolio.permalink.slug 
    
    class:
        work:           AppBundle\Entity\Portfolio\Work    
        tag:            AppBundle\Entity\Classification\Tag
        collection:     AppBundle\Entity\Classification\Collection
        media:          AppBundle\Entity\Media\Media
        gallery:        AppBundle\Entity\Media\Gallery
        user:           AppBundle\Entity\User\User
        

ivory_ck_editor:
    configs:
        portfolio:
            filebrowserBrowseRoute: admin_app_media_media_ckeditor_browser
            filebrowserImageBrowseRoute: admin_app_media_media_ckeditor_browser
            # Display images by default when clicking the image dialog browse button
            filebrowserImageBrowseRouteParameters:
                provider: sonata.media.provider.image
                hide_context: true
                context: portfolio
            filebrowserUploadRoute: admin_app_media_media_ckeditor_upload
            filebrowserUploadRouteParameters:
                provider: sonata.media.provider.file
                context: portfolio
            # Upload file as image when sending a file from the image dialog
            filebrowserImageUploadRoute: admin_app_media_media_ckeditor_upload
            filebrowserImageUploadRouteParameters:
                provider: sonata.media.provider.image
                #Optional, to upload in a custom context        
                context: portfolio 

sonata_media:
    contexts:
        portfolio:
            providers:
                - sonata.media.provider.image

            formats:
                small:    { width: 320, quality: 100}
                wide:     { width: 820, quality: 100}
