nz_wordpress:
    
    # Doctrine connection to use. Default is 'default'.
    table_prefix: "wp_"
    entity_manager: wp_manager
    
doctrine:
    dbal:

        connections:
            wp_connection:
                driver:   %database_driver%
                host:     %database_host%
                user:     %database_user%
                password: %database_password%
                dbname:   %wp_database_name%
                charset:  UTF8
                server_version: 5.5
                
    orm:
        entity_managers:
            wp_manager:
                connection: wp_connection
                mappings:  
                    NzWordpressBundle: ~

#
# more information can be found here https://sonata-project.org/bundles/admin
#
sonata_admin:

    dashboard:

        groups:
            sonata.admin.group.wp:
                label:           NzWordpress
                label_catalogue: AppBundle
                icon:            '<i class="fa fa-wordpress"></i>'
                items:
#                    - nz.migration.admin
                    - nz.wordpress.admin.user
                    - nz.wordpress.admin.users_metas
                    - nz.wordpress.admin.post
                    - nz.wordpress.admin.posts_metas
                    - nz.wordpress.admin.taxonomy
                    - nz.wordpress.admin.term
                    - nz.wordpress.admin.comment
                    - nz.wordpress.admin.option
