<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20161122170719 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE basket__basket_element DROP FOREIGN KEY FK_4538CA2C1BE1FB52');
        $this->addSql('ALTER TABLE classification__category DROP FOREIGN KEY FK_43629B36E25D857E');
        $this->addSql('ALTER TABLE classification__collection DROP FOREIGN KEY FK_A406B56AE25D857E');
        $this->addSql('ALTER TABLE classification__tag DROP FOREIGN KEY FK_CA57A1C7E25D857E');
        $this->addSql('ALTER TABLE basket__basket DROP FOREIGN KEY FK_1FD2A7E19395C3F3');
        $this->addSql('ALTER TABLE customer__address DROP FOREIGN KEY FK_55C3CDD39395C3F3');
        $this->addSql('ALTER TABLE invoice__invoice DROP FOREIGN KEY FK_FB05AC619395C3F3');
        $this->addSql('ALTER TABLE order__order DROP FOREIGN KEY FK_BC9E6FD19395C3F3');
        $this->addSql('ALTER TABLE invoice__invoice_element DROP FOREIGN KEY FK_C66B56842989F1FD');
        $this->addSql('ALTER TABLE nz__crawler_link DROP FOREIGN KEY FK_2DA0FAFFCCFA12B8');
        $this->addSql('ALTER TABLE nz__cron_job_result DROP FOREIGN KEY FK_CF323109BE04EA9');
        $this->addSql('ALTER TABLE nz__cron_job DROP FOREIGN KEY FK_2E0B148B14691BE8');
        $this->addSql('ALTER TABLE order__order_element DROP FOREIGN KEY FK_701A67EC8D9F6D38');
        $this->addSql('ALTER TABLE payment__transaction DROP FOREIGN KEY FK_4A7A00358D9F6D38');
        $this->addSql('ALTER TABLE invoice__invoice_element DROP FOREIGN KEY FK_C66B5684ACC5D771');
        $this->addSql('ALTER TABLE product__delivery DROP FOREIGN KEY FK_77E11FFD4584665A');
        $this->addSql('ALTER TABLE product__package DROP FOREIGN KEY FK_6190EC7F4584665A');
        $this->addSql('ALTER TABLE product__product DROP FOREIGN KEY FK_6CB28F47727ACA70');
        $this->addSql('ALTER TABLE product__product_category DROP FOREIGN KEY FK_D0B834B14584665A');
        $this->addSql('ALTER TABLE product__product_collection DROP FOREIGN KEY FK_96AD96454584665A');
        $this->addSql('ALTER TABLE test_car_inspection DROP FOREIGN KEY FK_B4624299C3C6F69F');
        $this->addSql('ALTER TABLE test_car DROP FOREIGN KEY FK_E403A5A124A1CAE');
        $this->addSql('ALTER TABLE test_car DROP FOREIGN KEY FK_E403A5AE78C9C0A');
        $this->addSql('ALTER TABLE test_car DROP FOREIGN KEY FK_E403A5A354AA425589740CE28FDB4419F71D163');
        $this->addSql('ALTER TABLE test_color DROP FOREIGN KEY FK_6D88EEE2E308AC6F');
        $this->addSql('DROP TABLE basket__basket');
        $this->addSql('DROP TABLE basket__basket_element');
        $this->addSql('DROP TABLE classification__category_audit');
        $this->addSql('DROP TABLE classification__collection_audit');
        $this->addSql('DROP TABLE classification__context');
        $this->addSql('DROP TABLE classification__context_audit');
        $this->addSql('DROP TABLE classification__tag_audit');
        $this->addSql('DROP TABLE comment__comment_audit');
        $this->addSql('DROP TABLE comment__thread_audit');
        $this->addSql('DROP TABLE customer__address');
        $this->addSql('DROP TABLE customer__address_audit');
        $this->addSql('DROP TABLE customer__customer');
        $this->addSql('DROP TABLE customer__customer_audit');
        $this->addSql('DROP TABLE fos_user_group_audit');
        $this->addSql('DROP TABLE fos_user_user_audit');
        $this->addSql('DROP TABLE invoice__invoice');
        $this->addSql('DROP TABLE invoice__invoice_audit');
        $this->addSql('DROP TABLE invoice__invoice_element');
        $this->addSql('DROP TABLE media__gallery_audit');
        $this->addSql('DROP TABLE media__gallery_media_audit');
        $this->addSql('DROP TABLE media__media_audit');
        $this->addSql('DROP TABLE news__comment_audit');
        $this->addSql('DROP TABLE news__post_audit');
        $this->addSql('DROP TABLE notification__message_audit');
        $this->addSql('DROP TABLE nz__crawler_crawled');
        $this->addSql('DROP TABLE nz__crawler_link');
        $this->addSql('DROP TABLE nz__crawler_profile');
        $this->addSql('DROP TABLE nz__cron_job');
        $this->addSql('DROP TABLE nz__cron_job_result');
        $this->addSql('DROP TABLE order__order');
        $this->addSql('DROP TABLE order__order_audit');
        $this->addSql('DROP TABLE order__order_element');
        $this->addSql('DROP TABLE order__order_element_audit');
        $this->addSql('DROP TABLE page__block_audit');
        $this->addSql('DROP TABLE page__page_audit');
        $this->addSql('DROP TABLE page__site_audit');
        $this->addSql('DROP TABLE page__snapshot_audit');
        $this->addSql('DROP TABLE payment__transaction');
        $this->addSql('DROP TABLE product__delivery');
        $this->addSql('DROP TABLE product__delivery_audit');
        $this->addSql('DROP TABLE product__package');
        $this->addSql('DROP TABLE product__product');
        $this->addSql('DROP TABLE product__product_audit');
        $this->addSql('DROP TABLE product__product_category');
        $this->addSql('DROP TABLE product__product_category_audit');
        $this->addSql('DROP TABLE product__product_collection');
        $this->addSql('DROP TABLE product__product_collection_audit');
        $this->addSql('DROP TABLE revisions');
        $this->addSql('DROP TABLE test_car');
        $this->addSql('DROP TABLE test_car_audit');
        $this->addSql('DROP TABLE test_car_engine');
        $this->addSql('DROP TABLE test_car_engine_audit');
        $this->addSql('DROP TABLE test_car_inspection');
        $this->addSql('DROP TABLE test_car_inspection_audit');
        $this->addSql('DROP TABLE test_color');
        $this->addSql('DROP TABLE test_color_audit');
        $this->addSql('DROP TABLE test_material');
        $this->addSql('DROP TABLE test_material_audit');
        $this->addSql('ALTER TABLE fos_user_user CHANGE biography biography VARCHAR(255) DEFAULT NULL');
        $this->addSql('CREATE INDEX notification_message_state_idx ON notification__message (state)');
        $this->addSql('CREATE INDEX notification_message_created_at_idx ON notification__message (created_at)');
        $this->addSql('DROP INDEX tag_collection ON classification__collection');
        $this->addSql('DROP INDEX IDX_A406B56AE25D857E ON classification__collection');
        $this->addSql('ALTER TABLE classification__collection DROP context');
        $this->addSql('ALTER TABLE timeline__timeline DROP FOREIGN KEY FK_FFBC6AD523EDC87');
        $this->addSql('ALTER TABLE timeline__timeline DROP FOREIGN KEY FK_FFBC6AD59D32F035');
        $this->addSql('DROP INDEX IDX_FFBC6AD59D32F035 ON timeline__timeline');
        $this->addSql('DROP INDEX IDX_FFBC6AD523EDC87 ON timeline__timeline');
        $this->addSql('ALTER TABLE timeline__timeline DROP subject_id, DROP action_id');
        $this->addSql('ALTER TABLE media__media DROP FOREIGN KEY FK_5C6DD74E12469DE2');
        $this->addSql('DROP INDEX IDX_5C6DD74E12469DE2 ON media__media');
        $this->addSql('ALTER TABLE media__media DROP category_id, DROP cdn_flush_identifier');
        $this->addSql('ALTER TABLE timeline__action_component DROP FOREIGN KEY FK_6ACD1B169D32F035');
        $this->addSql('ALTER TABLE timeline__action_component DROP FOREIGN KEY FK_6ACD1B16E2ABAFFF');
        $this->addSql('DROP INDEX IDX_6ACD1B169D32F035 ON timeline__action_component');
        $this->addSql('DROP INDEX IDX_6ACD1B16E2ABAFFF ON timeline__action_component');
        $this->addSql('ALTER TABLE timeline__action_component DROP action_id, DROP component_id');
        $this->addSql('DROP INDEX tag_context ON classification__tag');
        $this->addSql('DROP INDEX IDX_CA57A1C7E25D857E ON classification__tag');
        $this->addSql('ALTER TABLE classification__tag DROP context');
        $this->addSql('DROP INDEX IDX_43629B36E25D857E ON classification__category');
        $this->addSql('ALTER TABLE classification__category DROP context');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE basket__basket (id INT AUTO_INCREMENT NOT NULL, customer_id INT DEFAULT NULL, positions LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:json)\', delivery_address_id INT DEFAULT NULL, billing_address_id INT DEFAULT NULL, payment_method_code VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, cpt_element INT DEFAULT NULL, delivery_method_code VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, options LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:json)\', locale VARCHAR(6) DEFAULT NULL COLLATE utf8_unicode_ci, currency CHAR(3) DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_1FD2A7E19395C3F3 (customer_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE basket__basket_element (id INT AUTO_INCREMENT NOT NULL, basket_id INT DEFAULT NULL, product_id INT NOT NULL, position INT NOT NULL, vat_rate VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, unit_price VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, price VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, quantity INT NOT NULL, options LONGTEXT NOT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:json)\', name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, product_code VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, INDEX IDX_4538CA2C1BE1FB52 (basket_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE classification__category_audit (id INT NOT NULL, rev INT NOT NULL, parent_id INT DEFAULT NULL, context VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, media_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, enabled TINYINT(1) DEFAULT NULL, slug VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, description VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, position INT DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, revtype VARCHAR(4) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE classification__collection_audit (id INT NOT NULL, rev INT NOT NULL, context VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, media_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, enabled TINYINT(1) DEFAULT NULL, slug VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, description VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, revtype VARCHAR(4) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE classification__context (id VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE classification__context_audit (id VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, rev INT NOT NULL, name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, enabled TINYINT(1) DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, revtype VARCHAR(4) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE classification__tag_audit (id INT NOT NULL, rev INT NOT NULL, context VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, enabled TINYINT(1) DEFAULT NULL, slug VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, revtype VARCHAR(4) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE comment__comment_audit (id INT NOT NULL, rev INT NOT NULL, thread_id VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, body LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, ancestors VARCHAR(1024) DEFAULT NULL COLLATE utf8_unicode_ci, depth INT DEFAULT NULL, created_at DATETIME DEFAULT NULL, state INT DEFAULT NULL, author_name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, email VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, website VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, note DOUBLE PRECISION DEFAULT NULL, private TINYINT(1) DEFAULT NULL, revtype VARCHAR(4) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE comment__thread_audit (id VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, rev INT NOT NULL, category_id INT DEFAULT NULL, permalink VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, is_commentable TINYINT(1) DEFAULT NULL, num_comments INT DEFAULT NULL, last_comment_at DATETIME DEFAULT NULL, average_note DOUBLE PRECISION DEFAULT NULL, revtype VARCHAR(4) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer__address (id INT AUTO_INCREMENT NOT NULL, customer_id INT DEFAULT NULL, is_current TINYINT(1) NOT NULL, type INT NOT NULL, name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, firstname VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, lastname VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, address1 VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, address2 VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, address3 VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, postcode VARCHAR(12) NOT NULL COLLATE utf8_unicode_ci, city VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, country_code VARCHAR(3) NOT NULL COLLATE utf8_unicode_ci, phone VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, updated_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, INDEX IDX_55C3CDD39395C3F3 (customer_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer__address_audit (id INT NOT NULL, rev INT NOT NULL, customer_id INT DEFAULT NULL, is_current TINYINT(1) DEFAULT NULL, type INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, firstname VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, lastname VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, address1 VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, address2 VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, address3 VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, postcode VARCHAR(12) DEFAULT NULL COLLATE utf8_unicode_ci, city VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, country_code VARCHAR(3) DEFAULT NULL COLLATE utf8_unicode_ci, phone VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, updated_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, revtype VARCHAR(4) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer__customer (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, title INT DEFAULT NULL, firstname VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, lastname VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, email VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, birth_date DATETIME DEFAULT NULL, birth_place VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, phone_number VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, mobile_number VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, fax_number VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, locale VARCHAR(6) DEFAULT NULL COLLATE utf8_unicode_ci, updated_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, is_fake TINYINT(1) DEFAULT NULL, INDEX IDX_4043373A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE customer__customer_audit (id INT NOT NULL, rev INT NOT NULL, user_id INT DEFAULT NULL, title INT DEFAULT NULL, firstname VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, lastname VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, email VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, birth_date DATETIME DEFAULT NULL, birth_place VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, phone_number VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, mobile_number VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, fax_number VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, locale VARCHAR(6) DEFAULT NULL COLLATE utf8_unicode_ci, updated_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, is_fake TINYINT(1) DEFAULT NULL, revtype VARCHAR(4) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fos_user_group_audit (id INT NOT NULL, rev INT NOT NULL, name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, roles LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:array)\', revtype VARCHAR(4) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fos_user_user_audit (id INT NOT NULL, rev INT NOT NULL, username VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, username_canonical VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, email VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, email_canonical VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, enabled TINYINT(1) DEFAULT NULL, salt VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, password VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, last_login DATETIME DEFAULT NULL, locked TINYINT(1) DEFAULT NULL, expired TINYINT(1) DEFAULT NULL, expires_at DATETIME DEFAULT NULL, confirmation_token VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:array)\', credentials_expired TINYINT(1) DEFAULT NULL, credentials_expire_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, date_of_birth DATETIME DEFAULT NULL, firstname VARCHAR(64) DEFAULT NULL COLLATE utf8_unicode_ci, lastname VARCHAR(64) DEFAULT NULL COLLATE utf8_unicode_ci, website VARCHAR(64) DEFAULT NULL COLLATE utf8_unicode_ci, biography VARCHAR(1000) DEFAULT NULL COLLATE utf8_unicode_ci, gender VARCHAR(1) DEFAULT NULL COLLATE utf8_unicode_ci, locale VARCHAR(8) DEFAULT NULL COLLATE utf8_unicode_ci, timezone VARCHAR(64) DEFAULT NULL COLLATE utf8_unicode_ci, phone VARCHAR(64) DEFAULT NULL COLLATE utf8_unicode_ci, facebook_uid VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, facebook_name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, facebook_data LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:json)\', twitter_uid VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, twitter_name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, twitter_data LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:json)\', gplus_uid VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, gplus_name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, gplus_data LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:json)\', token VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, two_step_code VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, revtype VARCHAR(4) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE invoice__invoice (id INT AUTO_INCREMENT NOT NULL, customer_id INT DEFAULT NULL, reference VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, currency CHAR(3) NOT NULL COLLATE utf8_unicode_ci, status INT NOT NULL, total_inc NUMERIC(10, 4) NOT NULL, total_excl NUMERIC(10, 4) NOT NULL, name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, phone VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, address1 VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, address2 VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, address3 VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, city VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, postcode VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, country VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, fax VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, email VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, mobile VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, payment_method VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, locale VARCHAR(5) DEFAULT NULL COLLATE utf8_unicode_ci, created_at DATETIME DEFAULT NULL, INDEX IDX_FB05AC619395C3F3 (customer_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE invoice__invoice_audit (id INT NOT NULL, rev INT NOT NULL, customer_id INT DEFAULT NULL, reference VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, currency CHAR(3) DEFAULT NULL COLLATE utf8_unicode_ci, status INT DEFAULT NULL, total_inc NUMERIC(10, 4) DEFAULT NULL, total_excl NUMERIC(10, 4) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, phone VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, address1 VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, address2 VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, address3 VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, city VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, postcode VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, country VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, fax VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, email VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, mobile VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, payment_method VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, locale VARCHAR(5) DEFAULT NULL COLLATE utf8_unicode_ci, created_at DATETIME DEFAULT NULL, revtype VARCHAR(4) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE invoice__invoice_element (id INT AUTO_INCREMENT NOT NULL, invoice_id INT DEFAULT NULL, order_element_id INT DEFAULT NULL, quantity INT NOT NULL, unit_price_excl NUMERIC(10, 4) NOT NULL, unit_price_inc NUMERIC(10, 4) NOT NULL, price NUMERIC(10, 4) NOT NULL, vat_rate NUMERIC(10, 4) NOT NULL, total NUMERIC(10, 4) NOT NULL, designation VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, description LONGTEXT NOT NULL COLLATE utf8_unicode_ci, INDEX IDX_C66B56842989F1FD (invoice_id), INDEX IDX_C66B5684ACC5D771 (order_element_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE media__gallery_audit (id INT NOT NULL, rev INT NOT NULL, name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, context VARCHAR(64) DEFAULT NULL COLLATE utf8_unicode_ci, default_format VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, enabled TINYINT(1) DEFAULT NULL, updated_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, revtype VARCHAR(4) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE media__gallery_media_audit (id INT NOT NULL, rev INT NOT NULL, gallery_id INT DEFAULT NULL, media_id INT DEFAULT NULL, position INT DEFAULT NULL, enabled TINYINT(1) DEFAULT NULL, updated_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, revtype VARCHAR(4) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE media__media_audit (id INT NOT NULL, rev INT NOT NULL, category_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, description TEXT DEFAULT NULL COLLATE utf8_unicode_ci, enabled TINYINT(1) DEFAULT NULL, provider_name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, provider_status INT DEFAULT NULL, provider_reference VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, provider_metadata LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:json)\', width INT DEFAULT NULL, height INT DEFAULT NULL, length NUMERIC(10, 0) DEFAULT NULL, content_type VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, content_size INT DEFAULT NULL, copyright VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, author_name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, context VARCHAR(64) DEFAULT NULL COLLATE utf8_unicode_ci, cdn_is_flushable TINYINT(1) DEFAULT NULL, cdn_flush_identifier VARCHAR(64) DEFAULT NULL COLLATE utf8_unicode_ci, cdn_flush_at DATETIME DEFAULT NULL, cdn_status INT DEFAULT NULL, updated_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, revtype VARCHAR(4) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE news__comment_audit (id INT NOT NULL, rev INT NOT NULL, post_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, url VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, email VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, message LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, status INT DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, revtype VARCHAR(4) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE news__post_audit (id INT NOT NULL, rev INT NOT NULL, image_id INT DEFAULT NULL, author_id INT DEFAULT NULL, collection_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, abstract LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, content LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, raw_content LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, content_formatter VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, enabled TINYINT(1) DEFAULT NULL, slug VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, publication_date_start DATETIME DEFAULT NULL, comments_enabled TINYINT(1) DEFAULT NULL, comments_close_at DATETIME DEFAULT NULL, comments_default_status INT DEFAULT NULL, comments_count INT DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, revtype VARCHAR(4) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE notification__message_audit (id INT NOT NULL, rev INT NOT NULL, type VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, body LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:json)\', state INT DEFAULT NULL, restart_count INT DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, started_at DATETIME DEFAULT NULL, completed_at DATETIME DEFAULT NULL, revtype VARCHAR(4) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE nz__crawler_crawled (id INT AUTO_INCREMENT NOT NULL, image_id INT DEFAULT NULL, gallery_id INT DEFAULT NULL, date DATETIME NOT NULL, content LONGTEXT NOT NULL COLLATE utf8_unicode_ci, title VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, excerpt LONGTEXT NOT NULL COLLATE utf8_unicode_ci, enabled TINYINT(1) NOT NULL, source VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_6D02B2AD5F8A7F73 (source), INDEX IDX_6D02B2AD3DA5256D (image_id), INDEX IDX_6D02B2AD4E7AF8F (gallery_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE nz__crawler_link (id INT AUTO_INCREMENT NOT NULL, profile_id INT DEFAULT NULL, link_text VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, crawled_url VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, processed TINYINT(1) NOT NULL, has_error TINYINT(1) NOT NULL, skip TINYINT(1) NOT NULL, note LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:array)\', items LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, crawled_at DATETIME NOT NULL, UNIQUE INDEX profile_link_idx (crawled_url, profile_id), INDEX IDX_2DA0FAFFCCFA12B8 (profile_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE nz__crawler_profile (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, config LONGTEXT NOT NULL COLLATE utf8_unicode_ci, processed TINYINT(1) NOT NULL, enabled TINYINT(1) NOT NULL, last_processed_at DATETIME DEFAULT NULL, last_processed_status VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE nz__cron_job (id INT AUTO_INCREMENT NOT NULL, command VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, description VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, job_interval VARCHAR(40) NOT NULL COLLATE utf8_unicode_ci, nextRun DATETIME NOT NULL, enabled TINYINT(1) NOT NULL, mostRecentRun_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_2E0B148B14691BE8 (mostRecentRun_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE nz__cron_job_result (id INT AUTO_INCREMENT NOT NULL, job_id INT DEFAULT NULL, runAt DATETIME NOT NULL, runTime DOUBLE PRECISION NOT NULL, result INT NOT NULL, output LONGTEXT NOT NULL COLLATE utf8_unicode_ci, INDEX IDX_CF323109BE04EA9 (job_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE order__order (id INT AUTO_INCREMENT NOT NULL, customer_id INT DEFAULT NULL, reference VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, payment_method VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, delivery_method VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, currency CHAR(3) DEFAULT NULL COLLATE utf8_unicode_ci, status INT DEFAULT NULL, payment_status INT DEFAULT NULL, delivery_status INT DEFAULT NULL, validated_at DATETIME DEFAULT NULL, username VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, total_inc NUMERIC(10, 4) DEFAULT NULL, total_excl NUMERIC(10, 4) DEFAULT NULL, delivery_cost NUMERIC(10, 4) DEFAULT NULL, delivery_vat NUMERIC(10, 4) DEFAULT NULL, locale VARCHAR(6) DEFAULT NULL COLLATE utf8_unicode_ci, billing_name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, billing_phone VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, billing_address1 VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, billing_address2 VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, billing_address3 VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, billing_city VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, billing_postcode VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, billing_country_code VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, billing_fax VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, billing_email VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, billing_mobile VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shipping_name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shipping_phone VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shipping_address1 VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shipping_address2 VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shipping_address3 VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shipping_city VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shipping_postcode VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shipping_country_code VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shipping_fax VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shipping_email VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shipping_mobile VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, updated_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, INDEX IDX_BC9E6FD19395C3F3 (customer_id), INDEX order_status (status), INDEX payment_status (payment_status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE order__order_audit (id INT NOT NULL, rev INT NOT NULL, customer_id INT DEFAULT NULL, reference VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, payment_method VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, delivery_method VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, currency CHAR(3) DEFAULT NULL COLLATE utf8_unicode_ci, status INT DEFAULT NULL, payment_status INT DEFAULT NULL, delivery_status INT DEFAULT NULL, validated_at DATETIME DEFAULT NULL, username VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, total_inc NUMERIC(10, 4) DEFAULT NULL, total_excl NUMERIC(10, 4) DEFAULT NULL, delivery_cost NUMERIC(10, 4) DEFAULT NULL, delivery_vat NUMERIC(10, 4) DEFAULT NULL, locale VARCHAR(6) DEFAULT NULL COLLATE utf8_unicode_ci, billing_name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, billing_phone VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, billing_address1 VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, billing_address2 VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, billing_address3 VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, billing_city VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, billing_postcode VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, billing_country_code VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, billing_fax VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, billing_email VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, billing_mobile VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shipping_name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shipping_phone VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shipping_address1 VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shipping_address2 VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shipping_address3 VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shipping_city VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shipping_postcode VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shipping_country_code VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shipping_fax VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shipping_email VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, shipping_mobile VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, updated_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, revtype VARCHAR(4) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE order__order_element (id INT AUTO_INCREMENT NOT NULL, order_id INT DEFAULT NULL, product_id INT NOT NULL, product_type VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, quantity INT NOT NULL, unit_price_excl NUMERIC(10, 4) NOT NULL, unit_price_inc NUMERIC(10, 4) NOT NULL, price NUMERIC(10, 4) NOT NULL, vat_rate NUMERIC(10, 4) NOT NULL, designation VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, description LONGTEXT NOT NULL COLLATE utf8_unicode_ci, options LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:json)\', raw_product LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:json)\', status INT NOT NULL, delivery_status INT NOT NULL, validated_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, INDEX IDX_701A67EC8D9F6D38 (order_id), INDEX product_type (product_type), INDEX order_element_status (status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE order__order_element_audit (id INT NOT NULL, rev INT NOT NULL, order_id INT DEFAULT NULL, product_id INT DEFAULT NULL, product_type VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, quantity INT DEFAULT NULL, unit_price_excl NUMERIC(10, 4) DEFAULT NULL, unit_price_inc NUMERIC(10, 4) DEFAULT NULL, price NUMERIC(10, 4) DEFAULT NULL, vat_rate NUMERIC(10, 4) DEFAULT NULL, designation VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, description LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, options LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:json)\', raw_product LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:json)\', status INT DEFAULT NULL, delivery_status INT DEFAULT NULL, validated_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, revtype VARCHAR(4) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE page__block_audit (id INT NOT NULL, rev INT NOT NULL, parent_id INT DEFAULT NULL, page_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, type VARCHAR(64) DEFAULT NULL COLLATE utf8_unicode_ci, settings LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:json)\', enabled TINYINT(1) DEFAULT NULL, position INT DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, revtype VARCHAR(4) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE page__page_audit (id INT NOT NULL, rev INT NOT NULL, site_id INT DEFAULT NULL, parent_id INT DEFAULT NULL, target_id INT DEFAULT NULL, route_name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, page_alias VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, type VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, position INT DEFAULT NULL, enabled TINYINT(1) DEFAULT NULL, decorate TINYINT(1) DEFAULT NULL, edited TINYINT(1) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, slug LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, url LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, custom_url LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, request_method VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, title VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, meta_keyword VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, meta_description VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, javascript LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, stylesheet LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, raw_headers LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, template VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, revtype VARCHAR(4) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE page__site_audit (id INT NOT NULL, rev INT NOT NULL, enabled TINYINT(1) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, relative_path VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, host VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, enabled_from DATETIME DEFAULT NULL, enabled_to DATETIME DEFAULT NULL, is_default TINYINT(1) DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, locale VARCHAR(6) DEFAULT NULL COLLATE utf8_unicode_ci, title VARCHAR(64) DEFAULT NULL COLLATE utf8_unicode_ci, meta_keywords VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, meta_description VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, revtype VARCHAR(4) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE page__snapshot_audit (id INT NOT NULL, rev INT NOT NULL, site_id INT DEFAULT NULL, page_id INT DEFAULT NULL, route_name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, page_alias VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, type VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, position INT DEFAULT NULL, enabled TINYINT(1) DEFAULT NULL, decorate TINYINT(1) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, url LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, parent_id INT DEFAULT NULL, target_id INT DEFAULT NULL, content LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:json)\', publication_date_start DATETIME DEFAULT NULL, publication_date_end DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, revtype VARCHAR(4) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE payment__transaction (id INT AUTO_INCREMENT NOT NULL, order_id INT DEFAULT NULL, transaction_id VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, state INT NOT NULL, parameters LONGTEXT NOT NULL COLLATE utf8_unicode_ci COMMENT \'(DC2Type:json)\', status_code INT NOT NULL, payment_code VARCHAR(32) NOT NULL COLLATE utf8_unicode_ci, created_at DATETIME NOT NULL, information LONGTEXT NOT NULL COLLATE utf8_unicode_ci, INDEX IDX_4A7A00358D9F6D38 (order_id), INDEX status_code (status_code), INDEX state (state), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product__delivery (id INT AUTO_INCREMENT NOT NULL, product_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, per_item TINYINT(1) DEFAULT NULL, country_code VARCHAR(3) NOT NULL COLLATE utf8_unicode_ci, zone VARCHAR(5) DEFAULT NULL COLLATE utf8_unicode_ci, enabled TINYINT(1) NOT NULL, updated_at DATETIME NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_77E11FFD4584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product__delivery_audit (id INT NOT NULL, rev INT NOT NULL, product_id INT DEFAULT NULL, code VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, per_item TINYINT(1) DEFAULT NULL, country_code VARCHAR(3) DEFAULT NULL COLLATE utf8_unicode_ci, zone VARCHAR(5) DEFAULT NULL COLLATE utf8_unicode_ci, enabled TINYINT(1) DEFAULT NULL, updated_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, revtype VARCHAR(4) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product__package (id INT AUTO_INCREMENT NOT NULL, product_id INT DEFAULT NULL, width NUMERIC(10, 4) NOT NULL, height NUMERIC(10, 4) NOT NULL, length NUMERIC(10, 4) NOT NULL, weight NUMERIC(10, 4) NOT NULL, enabled TINYINT(1) NOT NULL, updated_at DATETIME NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_6190EC7F4584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product__product (id INT AUTO_INCREMENT NOT NULL, image_id INT DEFAULT NULL, gallery_id INT DEFAULT NULL, parent_id INT DEFAULT NULL, sku VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, slug VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, price_inc_vat TINYINT(1) NOT NULL, description LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, raw_description LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, description_formatter VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, short_description LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, raw_short_description LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, short_description_formatter VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, price NUMERIC(10, 2) DEFAULT NULL, vat_rate NUMERIC(10, 2) DEFAULT NULL, stock INT DEFAULT NULL, enabled TINYINT(1) DEFAULT NULL, updated_at DATETIME NOT NULL, created_at DATETIME NOT NULL, product_type VARCHAR(64) NOT NULL COLLATE utf8_unicode_ci, travellers INT DEFAULT NULL, travel_date DATETIME DEFAULT NULL, travel_days INT DEFAULT NULL, INDEX IDX_6CB28F473DA5256D (image_id), INDEX IDX_6CB28F474E7AF8F (gallery_id), INDEX IDX_6CB28F47727ACA70 (parent_id), INDEX enabled (enabled), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product__product_audit (id INT NOT NULL, rev INT NOT NULL, image_id INT DEFAULT NULL, gallery_id INT DEFAULT NULL, parent_id INT DEFAULT NULL, sku VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, slug VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, price_inc_vat TINYINT(1) DEFAULT NULL, description LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, raw_description LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, description_formatter VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, short_description LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, raw_short_description LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, short_description_formatter VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, price NUMERIC(10, 2) DEFAULT NULL, vat_rate NUMERIC(10, 2) DEFAULT NULL, stock INT DEFAULT NULL, enabled TINYINT(1) DEFAULT NULL, updated_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, product_type VARCHAR(64) DEFAULT NULL COLLATE utf8_unicode_ci, travellers INT DEFAULT NULL, travel_date DATETIME DEFAULT NULL, travel_days INT DEFAULT NULL, revtype VARCHAR(4) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product__product_category (id INT AUTO_INCREMENT NOT NULL, category_id INT DEFAULT NULL, product_id INT DEFAULT NULL, enabled TINYINT(1) NOT NULL, main TINYINT(1) DEFAULT NULL, updated_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, INDEX IDX_D0B834B14584665A (product_id), INDEX IDX_D0B834B112469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product__product_category_audit (id INT NOT NULL, rev INT NOT NULL, product_id INT DEFAULT NULL, category_id INT DEFAULT NULL, enabled TINYINT(1) DEFAULT NULL, main TINYINT(1) DEFAULT NULL, updated_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, revtype VARCHAR(4) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product__product_collection (id INT AUTO_INCREMENT NOT NULL, product_id INT DEFAULT NULL, collection_id INT DEFAULT NULL, enabled TINYINT(1) NOT NULL, updated_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, INDEX IDX_96AD96454584665A (product_id), INDEX IDX_96AD9645514956FD (collection_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product__product_collection_audit (id INT NOT NULL, rev INT NOT NULL, product_id INT DEFAULT NULL, collection_id INT DEFAULT NULL, enabled TINYINT(1) DEFAULT NULL, updated_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT NULL, revtype VARCHAR(4) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE revisions (id INT AUTO_INCREMENT NOT NULL, timestamp DATETIME NOT NULL, username VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE test_car (id INT AUTO_INCREMENT NOT NULL, color_r VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, color_g VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, color_b VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, color_material_id INT DEFAULT NULL, engine_id INT DEFAULT NULL, media_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL COLLATE utf8_unicode_ci, createdAt DATETIME NOT NULL, rescueEngine_id INT DEFAULT NULL, discr VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, INDEX IDX_E403A5AE78C9C0A (engine_id), INDEX IDX_E403A5A124A1CAE (rescueEngine_id), INDEX IDX_E403A5A354AA425589740CE28FDB4419F71D163 (color_r, color_g, color_b, color_material_id), INDEX IDX_E403A5AEA9FDD75 (media_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE test_car_audit (id INT NOT NULL, rev INT NOT NULL, engine_id INT DEFAULT NULL, color_r VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, color_g VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, color_b VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, color_material_id INT DEFAULT NULL, media_id INT DEFAULT NULL, name VARCHAR(100) DEFAULT NULL COLLATE utf8_unicode_ci, createdAt DATETIME DEFAULT NULL, rescueEngine_id INT DEFAULT NULL, discr VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, revtype VARCHAR(4) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE test_car_engine (id INT AUTO_INCREMENT NOT NULL, media_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL COLLATE utf8_unicode_ci, power INT NOT NULL, INDEX IDX_8BF34046EA9FDD75 (media_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE test_car_engine_audit (id INT NOT NULL, rev INT NOT NULL, media_id INT DEFAULT NULL, name VARCHAR(100) DEFAULT NULL COLLATE utf8_unicode_ci, power INT DEFAULT NULL, revtype VARCHAR(4) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE test_car_inspection (id INT AUTO_INCREMENT NOT NULL, car_id INT NOT NULL, inspector_id INT NOT NULL, date DATE NOT NULL, comment LONGTEXT NOT NULL COLLATE utf8_unicode_ci, status INT NOT NULL, INDEX IDX_B4624299C3C6F69F (car_id), INDEX IDX_B4624299D0E3F35F (inspector_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE test_car_inspection_audit (id INT NOT NULL, rev INT NOT NULL, car_id INT DEFAULT NULL, inspector_id INT DEFAULT NULL, date DATE DEFAULT NULL, comment LONGTEXT DEFAULT NULL COLLATE utf8_unicode_ci, status INT DEFAULT NULL, revtype VARCHAR(4) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE test_color (r VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, g VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, b VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, material_id INT NOT NULL, enabled TINYINT(1) NOT NULL, INDEX IDX_6D88EEE2E308AC6F (material_id), PRIMARY KEY(r, g, b, material_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE test_color_audit (r VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, g VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, b VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, material_id INT NOT NULL, rev INT NOT NULL, enabled TINYINT(1) DEFAULT NULL, revtype VARCHAR(4) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(r, g, b, material_id, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE test_material (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE test_material_audit (id INT NOT NULL, rev INT NOT NULL, name VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, revtype VARCHAR(4) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(id, rev)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE basket__basket ADD CONSTRAINT FK_1FD2A7E19395C3F3 FOREIGN KEY (customer_id) REFERENCES customer__customer (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE basket__basket_element ADD CONSTRAINT FK_4538CA2C1BE1FB52 FOREIGN KEY (basket_id) REFERENCES basket__basket (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE customer__address ADD CONSTRAINT FK_55C3CDD39395C3F3 FOREIGN KEY (customer_id) REFERENCES customer__customer (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE customer__customer ADD CONSTRAINT FK_4043373A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user_user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE invoice__invoice ADD CONSTRAINT FK_FB05AC619395C3F3 FOREIGN KEY (customer_id) REFERENCES customer__customer (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE invoice__invoice_element ADD CONSTRAINT FK_C66B56842989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice__invoice (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE invoice__invoice_element ADD CONSTRAINT FK_C66B5684ACC5D771 FOREIGN KEY (order_element_id) REFERENCES order__order_element (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE nz__crawler_crawled ADD CONSTRAINT FK_6D02B2AD3DA5256D FOREIGN KEY (image_id) REFERENCES media__media (id)');
        $this->addSql('ALTER TABLE nz__crawler_crawled ADD CONSTRAINT FK_6D02B2AD4E7AF8F FOREIGN KEY (gallery_id) REFERENCES media__gallery (id)');
        $this->addSql('ALTER TABLE nz__crawler_link ADD CONSTRAINT FK_2DA0FAFFCCFA12B8 FOREIGN KEY (profile_id) REFERENCES nz__crawler_profile (id)');
        $this->addSql('ALTER TABLE nz__cron_job ADD CONSTRAINT FK_2E0B148B14691BE8 FOREIGN KEY (mostRecentRun_id) REFERENCES nz__cron_job_result (id)');
        $this->addSql('ALTER TABLE nz__cron_job_result ADD CONSTRAINT FK_CF323109BE04EA9 FOREIGN KEY (job_id) REFERENCES nz__cron_job (id)');
        $this->addSql('ALTER TABLE order__order ADD CONSTRAINT FK_BC9E6FD19395C3F3 FOREIGN KEY (customer_id) REFERENCES customer__customer (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE order__order_element ADD CONSTRAINT FK_701A67EC8D9F6D38 FOREIGN KEY (order_id) REFERENCES order__order (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE payment__transaction ADD CONSTRAINT FK_4A7A00358D9F6D38 FOREIGN KEY (order_id) REFERENCES order__order (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE product__delivery ADD CONSTRAINT FK_77E11FFD4584665A FOREIGN KEY (product_id) REFERENCES product__product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product__package ADD CONSTRAINT FK_6190EC7F4584665A FOREIGN KEY (product_id) REFERENCES product__product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product__product ADD CONSTRAINT FK_6CB28F473DA5256D FOREIGN KEY (image_id) REFERENCES media__media (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE product__product ADD CONSTRAINT FK_6CB28F474E7AF8F FOREIGN KEY (gallery_id) REFERENCES media__gallery (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE product__product ADD CONSTRAINT FK_6CB28F47727ACA70 FOREIGN KEY (parent_id) REFERENCES product__product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product__product_category ADD CONSTRAINT FK_D0B834B112469DE2 FOREIGN KEY (category_id) REFERENCES classification__category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product__product_category ADD CONSTRAINT FK_D0B834B14584665A FOREIGN KEY (product_id) REFERENCES product__product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product__product_collection ADD CONSTRAINT FK_96AD96454584665A FOREIGN KEY (product_id) REFERENCES product__product (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product__product_collection ADD CONSTRAINT FK_96AD9645514956FD FOREIGN KEY (collection_id) REFERENCES classification__collection (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE test_car ADD CONSTRAINT FK_E403A5A124A1CAE FOREIGN KEY (rescueEngine_id) REFERENCES test_car_engine (id)');
        $this->addSql('ALTER TABLE test_car ADD CONSTRAINT FK_E403A5A354AA425589740CE28FDB4419F71D163 FOREIGN KEY (color_r, color_g, color_b, color_material_id) REFERENCES test_color (r, g, b, material_id)');
        $this->addSql('ALTER TABLE test_car ADD CONSTRAINT FK_E403A5AE78C9C0A FOREIGN KEY (engine_id) REFERENCES test_car_engine (id)');
        $this->addSql('ALTER TABLE test_car ADD CONSTRAINT FK_E403A5AEA9FDD75 FOREIGN KEY (media_id) REFERENCES media__media (id)');
        $this->addSql('ALTER TABLE test_car_engine ADD CONSTRAINT FK_8BF34046EA9FDD75 FOREIGN KEY (media_id) REFERENCES media__media (id)');
        $this->addSql('ALTER TABLE test_car_inspection ADD CONSTRAINT FK_B4624299C3C6F69F FOREIGN KEY (car_id) REFERENCES test_car (id)');
        $this->addSql('ALTER TABLE test_car_inspection ADD CONSTRAINT FK_B4624299D0E3F35F FOREIGN KEY (inspector_id) REFERENCES fos_user_user (id)');
        $this->addSql('ALTER TABLE test_color ADD CONSTRAINT FK_6D88EEE2E308AC6F FOREIGN KEY (material_id) REFERENCES test_material (id)');
        $this->addSql('ALTER TABLE classification__category ADD context VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci');
        $this->addSql('ALTER TABLE classification__category ADD CONSTRAINT FK_43629B36E25D857E FOREIGN KEY (context) REFERENCES classification__context (id)');
        $this->addSql('CREATE INDEX IDX_43629B36E25D857E ON classification__category (context)');
        $this->addSql('ALTER TABLE classification__collection ADD context VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci');
        $this->addSql('ALTER TABLE classification__collection ADD CONSTRAINT FK_A406B56AE25D857E FOREIGN KEY (context) REFERENCES classification__context (id)');
        $this->addSql('CREATE UNIQUE INDEX tag_collection ON classification__collection (slug, context)');
        $this->addSql('CREATE INDEX IDX_A406B56AE25D857E ON classification__collection (context)');
        $this->addSql('ALTER TABLE classification__tag ADD context VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci');
        $this->addSql('ALTER TABLE classification__tag ADD CONSTRAINT FK_CA57A1C7E25D857E FOREIGN KEY (context) REFERENCES classification__context (id)');
        $this->addSql('CREATE UNIQUE INDEX tag_context ON classification__tag (slug, context)');
        $this->addSql('CREATE INDEX IDX_CA57A1C7E25D857E ON classification__tag (context)');
        $this->addSql('ALTER TABLE fos_user_user CHANGE biography biography VARCHAR(1000) DEFAULT NULL COLLATE utf8_unicode_ci');
        $this->addSql('ALTER TABLE media__media ADD category_id INT DEFAULT NULL, ADD cdn_flush_identifier VARCHAR(64) DEFAULT NULL COLLATE utf8_unicode_ci');
        $this->addSql('ALTER TABLE media__media ADD CONSTRAINT FK_5C6DD74E12469DE2 FOREIGN KEY (category_id) REFERENCES classification__category (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_5C6DD74E12469DE2 ON media__media (category_id)');
        $this->addSql('DROP INDEX notification_message_state_idx ON notification__message');
        $this->addSql('DROP INDEX notification_message_created_at_idx ON notification__message');
        $this->addSql('ALTER TABLE timeline__action_component ADD action_id INT DEFAULT NULL, ADD component_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE timeline__action_component ADD CONSTRAINT FK_6ACD1B169D32F035 FOREIGN KEY (action_id) REFERENCES timeline__action (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE timeline__action_component ADD CONSTRAINT FK_6ACD1B16E2ABAFFF FOREIGN KEY (component_id) REFERENCES timeline__component (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX IDX_6ACD1B169D32F035 ON timeline__action_component (action_id)');
        $this->addSql('CREATE INDEX IDX_6ACD1B16E2ABAFFF ON timeline__action_component (component_id)');
        $this->addSql('ALTER TABLE timeline__timeline ADD subject_id INT DEFAULT NULL, ADD action_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE timeline__timeline ADD CONSTRAINT FK_FFBC6AD523EDC87 FOREIGN KEY (subject_id) REFERENCES timeline__component (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE timeline__timeline ADD CONSTRAINT FK_FFBC6AD59D32F035 FOREIGN KEY (action_id) REFERENCES timeline__action (id)');
        $this->addSql('CREATE INDEX IDX_FFBC6AD59D32F035 ON timeline__timeline (action_id)');
        $this->addSql('CREATE INDEX IDX_FFBC6AD523EDC87 ON timeline__timeline (subject_id)');
    }
}
