
sonata_media:
    contexts:
        default:
            providers:
                - sonata.media.provider.video
                - sonata.media.provider.sapo
                - sonata.media.provider.soundcloud
                - sonata.media.provider.playwire
                - sonata.media.provider.audio
