sonata_timeline:
    manager_type: orm

    class:
       component:            '%spy_timeline.class.component%'
       actionComponent:      '%spy_timeline.class.action_component%'
#       action_component:     '%spy_timeline.class.action_component%'
       action:               '%spy_timeline.class.action%'
       timeline:             '%spy_timeline.class.timeline%'

spy_timeline:
    drivers:
        orm:
            object_manager: doctrine.orm.entity_manager
            classes:
                query_builder: ~ # Spy\TimelineBundle\Driver\ORM\QueryBuilder\QueryBuilder
                timeline:         AppBundle\Entity\Timeline\Timeline
                action:           AppBundle\Entity\Timeline\Action
                component:        AppBundle\Entity\Timeline\Component
                action_component: AppBundle\Entity\Timeline\ActionComponent

    filters:
        data_hydrator:
            priority:             20
            service:              spy_timeline.filter.data_hydrator
            filter_unresolved:    false
            locators:
                - spy_timeline.filter.data_hydrator.locator.doctrine_orm

