#FROM mysql:5.6
FROM mariadb:10.1

#RUN ln -fs /usr/share/zoneinfo/Europe/Madrid /etc/localtime; \
#    dpkg-reconfigure -f noninteractive tzdata

#COPY etc/mysql/conf.d /etc/mysql/conf.d
#COPY etc/logrotate.d/mysql /etc/logrotate.d/mysql
#COPY var/schema /var/schema
#COPY var/migrations /var/migrations
#COPY var/fixtures /var/fixtures

#ADD bin/startup.sh /usr/src/startup.sh
#RUN chmod +x /usr/src/startup.sh && /usr/src/startup.sh
